namespace GwentCompanion.Core.Simulation;

/// <summary>
/// A conditional availability estimate. It assumes the current working deck hypothesis is correct; it is not the
/// probability that an inferred card belongs to the opponent's deck.
/// </summary>
public sealed record OpponentReachAssessment(
    string Ease,
    double? ConditionalAnswerInHand,
    int AnswerIdentities,
    int AnswerCopies,
    int LeadAnswerIdentities,
    int LeadAnswerCopies,
    string Reliability,
    double ReliabilityScore,
    int ExactModels,
    int EstimatedModels,
    string Detail);

public sealed record ReachValidationProfile(string Source, int ReviewedActions, int ExactMatches,
    double MeanAbsoluteError, string Scope, int MaximumComparisons = 0, int MaximumExactMatches = 0,
    double MaximumMeanOverstatement = 0)
{
    public double ExactRate => ReviewedActions == 0 ? 0 : (double)ExactMatches / ReviewedActions;

    // Regenerated by --reach-footage-regression from the reviewed 2026-08-27 and 2026-08-28 action windows.
    // This is deliberately a narrow calibration signal, not a claim of whole-catalog accuracy.
    public static ReachValidationProfile ReviewedFootage { get; } = new(
        "reviewed footage action replay", 10, 10, 0,
        "Chosen rows, targets, tutor/create choices, orders and random outcomes in ten reviewed footage segments.",
        7, 4, 12d / 7);
}

public static class OpponentReachModel
{
    /// <summary>Chance that at least one of <paramref name="copies"/> is in hand when hand/deck locations are unknown.</summary>
    public static double? ConditionalHandChance(int? handCount, int? deckCount, int copies)
    {
        if (copies <= 0) return 0;
        if (handCount is not { } hand || deckCount is not { } deck || hand < 0 || deck < 0) return null;
        var pool = hand + deck;
        if (pool <= 0) return 0;
        copies = Math.Min(copies, pool);
        hand = Math.Min(hand, pool);
        if (hand == 0) return 0;
        if (copies > deck) return 1;

        // P(no answer in hand) = choose(pool-copies, hand) / choose(pool, hand), evaluated as a stable product.
        var none = 1d;
        for (var draw = 0; draw < hand; draw++)
            none *= (double)(pool - copies - draw) / (pool - draw);
        return Math.Clamp(1 - none, 0, 1);
    }

    public static OpponentReachAssessment Assess(int? gap, IReadOnlyList<CatchUpThreat> replies,
        IReadOnlyList<ThreatCandidate> candidates, ThreatSummary? summary, IReadOnlyList<string> assumptions,
        ReachValidationProfile? validation = null)
    {
        var answers = replies.Select(reply => reply.Candidate).DistinctBy(candidate => candidate.Card.Id).ToArray();
        var answerCopies = answers.Sum(candidate => Math.Max(1, candidate.CopiesRemaining));
        var leadAnswers = replies.Where(reply => gap is null || reply.Points > gap).Select(reply => reply.Candidate)
            .DistinctBy(candidate => candidate.Card.Id).ToArray();
        var leadAnswerCopies = leadAnswers.Sum(candidate => Math.Max(1, candidate.CopiesRemaining));
        double? handChance = null;
        var known = leadAnswers.Where(candidate => candidate.ConditionalHandChance is not null).ToArray();
        if (known.Length > 0)
        {
            // Candidate events are not independent. Each identity estimate comes from the same hand/deck pool, so use
            // the strongest identity as a conservative floor rather than multiplying pseudo-independent events.
            handChance = known.Max(candidate => candidate.ConditionalHandChance);
        }

        var evaluated = summary?.EvaluatedCards ?? 0;
        var estimated = summary?.EstimatedCards ?? 0;
        var exact = Math.Max(0, evaluated - estimated);
        var candidateCoverage = summary is { CandidateCards: > 0 }
            ? Math.Clamp((double)evaluated / summary.CandidateCards, 0, 1) : 0;
        var exactCoverage = evaluated > 0 ? (double)exact / evaluated : 0;
        var validationRate = validation?.ExactRate ?? 0;
        var score = .45 * exactCoverage + .35 * candidateCoverage + .20 * validationRate;
        if (assumptions.Any(note => note.Contains("No fresh complete board", StringComparison.OrdinalIgnoreCase) ||
                                    note.Contains("Fresh exact board reconstruction was unavailable", StringComparison.OrdinalIgnoreCase)))
            score *= .7;
        score = Math.Clamp(score, 0, 1);
        var reliability = score >= .8 ? "high" : score >= .55 ? "medium" : "low";

        var ease = gap is < 0 ? "already ahead" : answers.Length == 0 ? "no supported answer" : leadAnswers.Length == 0 ? "tie only" : handChance switch
        {
            >= .70 => "easy",
            >= .40 => "reachable",
            >= .15 => "possible",
            < .15 => "difficult",
            _ => answers.Length >= 3 ? "reachable" : "possible"
        };
        var availability = handChance is { } chance
            ? $"At least {chance:P0} conditional hand availability for the strongest lead-taking identity"
            : leadAnswers.Length == 0 ? "No evaluated identity gets strictly ahead" :
              "Opponent hand/deck counts unavailable; lead-taking availability is unquantified";
        var benchmark = validation is null ? "No recorded-action calibration loaded" :
            $"{validation.ExactMatches}/{validation.ReviewedActions} reviewed chosen actions exact; MAE {validation.MeanAbsoluteError:0.00}. " +
            (validation.MaximumComparisons > 0
                ? $"Best-line bounds equaled the chosen result in {validation.MaximumExactMatches}/{validation.MaximumComparisons} comparable segments and averaged {validation.MaximumMeanOverstatement:0.00} points above it. "
                : "") + validation.Scope;
        var detail = $"{availability}. {leadAnswers.Length} lead-taking identities / {leadAnswerCopies} remaining hypothetical copies; " +
            $"{answers.Length} identities / {answerCopies} copies can at least tie. " +
            $"Model coverage {evaluated}/{summary?.CandidateCards ?? candidates.Count}; exact {exact}, estimated {estimated}. {benchmark}" +
            (estimated > 0 ? " Approximate/subtotal models do not establish an upper bound; no supported answer is not proof of a safe pass." : "");
        return new(ease, handChance, answers.Length, answerCopies, leadAnswers.Length, leadAnswerCopies,
            reliability, score, exact, estimated, detail);
    }
}
